# Generated by Django 3.2 on 2021-04-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Audiobook_file', models.FileField(upload_to='Audiobook')),
                ('Book_Title', models.CharField(max_length=100, unique=True)),
                ('Book_Author', models.CharField(max_length=100, unique=True)),
                ('Book_Narrator', models.IntegerField()),
                ('Upload_time', models.DateTimeField(auto_now_add=True)),
                ('Uploaded', models.BooleanField(default=False)),
            ],
        ),
    ]
