# Generated by Django 3.2 on 2021-04-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Podcast_file', models.FileField(upload_to='Podcast')),
                ('Podcast_name', models.CharField(max_length=100, unique=True)),
                ('Podcast_host', models.CharField(max_length=100, unique=True)),
                ('Podcast_duration', models.IntegerField()),
                ('Upload_time', models.DateTimeField(auto_now_add=True)),
                ('Uploaded', models.BooleanField(default=False)),
            ],
        ),
    ]
