# Generated by Django 3.2 on 2021-04-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField(unique=True)),
                ('Song_name', models.CharField(max_length=100)),
                ('Song_duration', models.IntegerField()),
                ('Upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
