# Generated by Django 3.2 on 2021-04-22 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='ID',
        ),
    ]
