# Generated by Django 3.2 on 2021-04-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0005_songs_song_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='Song_upload',
            field=models.FileField(upload_to='Songs'),
        ),
    ]
